config/routes.rb
Rails.application.routes.draw do

root :to => 'users#index'
resources :user_sessions
resources :users

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout


root "articles#index"
 resources :articles
 resources :user_sessions
 resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  protect_from_forgery with: :exception
  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def index
    @articles = Article.all
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :user_id)
  end

  def set_article
    @artilce = Article.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
          @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :second_name)
    end

    # Never trust parameters from the scary internet, only allow the white list through.

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="container">
<%= form_for(article) do |f| %>

<% if article.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:
  </h2>
  <ul>
    <% article.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
    <% end %>
  </ul>
</div>
<% end %>
<form>
  <div class="form-group">
<p>
  <%= f.label :title %> <br>
  <%= f.text_field :title, class: "form-control" %>
</p>
</div>
<div class="form-group">
<p>
  <%= f.label :content %> <br>
  <%= f.text_area :content, class: "form-control" %>
</p>
</div>
<p>
  <%= f.submit class: 'btn btn-success' %>
</p>
</div>
</form>
<% end %>
</div>

app/views/articles/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav">
              <li></li>
              </ul>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "All Articles", articles_path %></li>
        <li>  <%= link_to "New Article", new_article_path %> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/articles/edit.html.erb
<%= render 'nav' %>
<div class= "container">
  <div class ="jumbotron">
<h1> New Article </h1>
</div>
<%= render 'form', article: @article %>
</div>

app/views/articles/index.html.erb
<body>
  <%= render 'nav' %>
  <div class="container">
  <div class="jumbotron">
    <h1>The Weekly Daily</h1>
    <p>Browse all our new articles...</p>
  </div>
</div>



  <% @articles.each do |article| %>
  <div class="container">
  <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><%= article.title %> By <%= article.user.first_name %></div>
  <div class="panel-body">
    <p><%= article.content %></p>
  </div>

  <!-- List group -->
  <ul class="list-group">
    <li class="list-group-item"><%= link_to 'View full Article', article %></li>
    <li class="list-group-item"><%= link_to 'Edit', edit_article_path(article) %></li>
    <li class="list-group-item"><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></li>

  </ul>
</div>
</div>
  <% end %>

app/views/articles/new.html.erb
<%= render 'nav' %>
<div class= "container">
  <div class="jumbotron">
<h1> New Article </h1>
</div>
<%= render 'form', article: @article %>
</div>

app/views/articles/show.html.erb
<%= render 'nav' %>
<div class="container">
  <div class="jumbotron">
    <h1>
      <%= @article.title %>
    </h1>
    <h2>
      <%= @article.user.first_name %> <%= @article.user.second_name %>
    
    </h2>
  </div>

  <div class="container">
    <p>
      <%= @article.content %>
    </p>
  </div>
  <ul class="list-group">
    <li class="list-group-item"><%= link_to 'Edit', edit_article_path(@article) %></li>
    <li class="list-group-item"><%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  </ul>

</div>

app/views/home/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-*-1">
        <h1>The Weekly Daily</h1>
        <h2>Your Week's Worth Of News, Daily.</h2>
        <hr>
        <button class="btn btn-default btn-lg"><%= link_to "My Magazine Articles", controller: "articles" %></button>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutorial</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>

<div id="nav">
  <% if current_user %>
    <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
    <%= link_to "Logout", :logout, method: :post %>
  <% else %>
    <%= link_to "Register", new_user_path %> |
    <%= link_to "Login", :login %>
  <% end %>
</div>
<div>
  <p id="notice"><%= flash[:notice] %></p>
  <p id="alert"><%= flash[:alert] %></p>
</div>
<%= yield %>

</body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<div class="container">
<%= form_with(model: user, local: true) do |f| %>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form>
    <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

<div class="form-group">
  <p>
    <%= f.label :second_name %>
    <%= f.text_field :second_name, class: "form-control" %>
  </p>
  </div>

<div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, id: :user_email, class: "form-control" %>
  </div>

<div class="form-group">
     <%= f.label :password %><br />
     <%= f.password_field :password, class: "form-control" %>
  </div>

<div class="form-group">
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
</form>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>